apiVersion: v1
kind: ConfigMap
metadata:
  name: "config-epamdemotest"
  namespace: "agents-platform-eng"
data:
  AGENT_ID: "epamdemotest"
  TEAM_NAME: "platform-eng"
  PLATFORM_REGISTRY_URL: "https://apim-agenticdemo-poc.azure-api.net"
  KEYVAULT_URL: "https://kv-agenticdemo-poc.vault.azure.net/"
  AZURE_OPENAI_ENDPOINT: "https://oai-agenticdemo-poc.openai.azure.com/"
  AZURE_OPENAI_DEPLOYMENT: "gpt-4o"
  OTEL_SERVICE_NAME: "epamdemotest"
