apiVersion: v1
kind: Service
metadata:
  name: "epamdemotest"
  namespace: "agents-platform-eng"
spec:
  selector:
    app: "epamdemotest"
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
